version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - /opt/smarthome/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /opt/smarthome/home-assistant/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /opt/smarthome/home-assistant/certs/privkey.pem:/certs/privkey.pem:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mqtt
      - influxdb
    restart: always
    network_mode: host
    ports:
      - "8123:8123"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - /opt/smarthome/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/smarthome/mosquitto/data:/mosquitto/data
      - /opt/smarthome/mosquitto/log:/mosquitto/log:rw
      - /opt/smarthome/mosquitto/certs:/mosquitto/certs

  influxdb:
    container_name: influxdb
    image: influxdb
    ports: 
      - "8086:8086"
    volumes:
      - /opt/smarthome/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /opt/smarthome/influxdb/influxdb:/var/lib/influxdb
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    volumes:
      - /opt/smarthome/grafana/grafana:/var/lib/grafana
      - /opt/smarthome/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/smarthome/grafana/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /opt/smarthome/grafana/certs/privkey.pem:/certs/privkey.pem:ro
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    volumes:
      - /opt/smarthome/pihole/pihole:/etc/pihole
      - /opt/smarthome/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /opt/smarthome/pihole/lighttpd/external.conf:/etc/lighttpd/external.conf
      - /opt/smarthome/pihole/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /opt/smarthome/pihole/certs/combined.pem:/certs/combined.pem:ro
    environment:
      - "ServerIP="
    ports:
      - "53:53/tcp" 
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - "NET_ADMIN"

