version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - /opt/smarthome/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /opt/smarthome/home-assistant/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /opt/smarthome/home-assistant/certs/privkey.pem:/certs/privkey.pem:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mqtt
      - influxdb
      - sql
    restart: always
    #network_mode: host
    ports:
      - "8123:8123"
    networks:
      - frontend
      - backend

  sql:
    container_name: sql
    image: postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/smarthome/sql/data:/var/lib/postgresql/data
      - /opt/smarthome/sql/etc/postgresql:/etc/postgresql
      - /opt/smarthome/sql//var/log/postgresql:/var/log/postgresql
    networks:
      - backend

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - /opt/smarthome/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/smarthome/mosquitto/data:/mosquitto/data
      - /opt/smarthome/mosquitto/log:/mosquitto/log:rw
      - /opt/smarthome/mosquitto/certs:/mosquitto/certs
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    networks:
      - frontend
      - backend

  ot-recorder:
    container_name: ot-recorder
    image: owntracks/recorder
    environment:
      - "OTR_HOST=mqtt"
    volumes:
      - recorder-data:/store
    ports:
      - 8083:8083
    networks:
      - frontend
    depends_on:
      - mqtt

  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - /opt/smarthome/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /opt/smarthome/influxdb/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - frontend
      - backend
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    user: "0"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-worldmap-panel"
    volumes:
      - /opt/smarthome/grafana/grafana:/var/lib/grafana
      - /opt/smarthome/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/smarthome/grafana/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /opt/smarthome/grafana/certs/privkey.pem:/certs/privkey.pem:ro
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      - backend
  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    volumes:
      - /opt/smarthome/pihole/pihole:/etc/pihole
      - /opt/smarthome/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /opt/smarthome/pihole/lighttpd/external.conf:/etc/lighttpd/external.conf
      - /opt/smarthome/pihole/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /opt/smarthome/pihole/certs/combined.pem:/certs/combined.pem:ro
    environment:
      - "ServerIP="
    ports:
      - "53:53/tcp" 
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - frontend
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - "NET_ADMIN"

volumes:
  recorder-data:

networks:
  frontend:
  backend:
