
- platform: teksavvy
  api_key: !secret teksavvy_api_key
  total_bandwidth: 0
  monitored_variables:
  - usage
  - usage_gb
  - limit
  - onpeak_download
  - onpeak_upload
  - onpeak_total
  - offpeak_download
  - offpeak_upload
  - offpeak_total
  - onpeak_remaining

- platform: plex
  host: !secret plex_host
  port: !secret plex_port
  name: !secret plex_name
  username: !secret plex_famflix_username
  password: !secret plex_famflix_password

- platform: apcupsd
  resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - status
      - timeleft
      - tonbatt

        #- platform: pi_hole
        #  host: !secret pi_hole_host
        #  monitored_conditions:
        #  - ads_blocked_today
        #  - ads_percentage_today
        #  - dns_queries_today
        #  - domains_being_blocked
        #  - queries_cached
        #  - queries_forwarded
        #  - unique_domains
        #  - unique_clients
        #  - clients_ever_seen

