
- platform: teksavvy
  api_key: !secret teksavvy_api_key
  total_bandwidth: 0
  monitored_variables:
  - usage
  - usage_gb
  - limit
  - onpeak_download
  - onpeak_upload
  - onpeak_total
  - offpeak_download
  - offpeak_upload
  - offpeak_total
  - onpeak_remaining

- platform: plex
  host: !secret plex_host
  port: !secret plex_port
  name: !secret plex_name
  username: !secret plex_famflix_username
  password: !secret plex_famflix_password

- platform: apcupsd
  resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - status
      - timeleft
      - tonbatt

- platform: mqtt
  state_topic: !secret mqtt_sensor1_device1_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: !secret mqtt_sensor1_device1_name
- platform: mqtt
  state_topic: !secret mqtt_sensor2_device1_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: !secret mqtt_sensor2_device1_name
- platform: mqtt
  state_topic: !secret mqtt_sensor3_device1_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: !secret mqtt_sensor3_device1_name

- platform: min_max
  name: !secret device1_occupancy_name
  type: max
  round_digits: 0
  entity_ids:
    - !secret monitor_sensor1_device1
    - !secret monitor_sensor2_device1
    - !secret monitor_sensor3_device1

- platform: mqtt
  state_topic: !secret mqtt_sensor1_device2_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: !secret mqtt_sensor1_device2_name
- platform: mqtt
  state_topic: !secret mqtt_sensor2_device2_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: !secret mqtt_sensor2_device2_name
- platform: mqtt
  state_topic: !secret mqtt_sensor3_device2_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: !secret mqtt_sensor3_device2_name

- platform: min_max
  name: !secret device2_occupancy_name
  type: max
  round_digits: 0
  entity_ids:
    - !secret monitor_sensor1_device2
    - !secret monitor_sensor2_device2
    - !secret monitor_sensor3_device2

